apiVersion: apps/v1
kind: Deployment
metadata:
  name: articles-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: articles-operator
  template:
    metadata:
      labels:
        name: articles-operator
    spec:
      serviceAccountName: articles-operator
      containers:
        - name: articles-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "articles-operator"
