apiVersion: apps/v1
kind: Deployment
metadata:
  name: articlesdb
spec:
  selector:
    matchLabels:
      app: articlesdb
  replicas: 1
  template:
    metadata:
      labels:
        app: articlesdb
    spec:
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: "POSTGRES_PASSWORD"
              value: {{ .Values.global.postgresqlPassword }}
            - name: "POSTGRES_USER"
              value: {{ .Values.global.postgresqlUsername }}
            - name: "POSTGRES_DB"
              value: {{ .Values.global.postgresqlDatabase }}
